name: Build and Push Docker Image

on:
  push:
    branches:
      - main 
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev  # Add the environment name

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in to Docker Hub securely using secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Get short commit SHA
      - name: Get short commit SHA
        id: short_sha
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      # Step 5: Get current date (YYYY-MM-DD)
      - name: Get current date
        id: date_time
        run: echo "DATE_TIME=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      # Step 6: Get current time (HH-MM-SS)
      - name: Get current time
        id: current_time
        run: echo "TIME=$(date -u +'%H-%M-%S')" >> $GITHUB_ENV

      # Step 7: Build and push Docker image with dynamic tags
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            sachinfe/cmi-behavior-classifier:latest
            sachinfe/cmi-behavior-classifier:${{ github.ref_name }}
            sachinfe/cmi-behavior-classifier:${{ env.SHORT_SHA }}
            sachinfe/cmi-behavior-classifier:${{ github.ref_name }}-${{ env.DATE_TIME }}-${{ env.TIME }}